package com.jiyun.qcloud.dashixummoban.dom;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jiyun.qcloud.dashixummoban.entity.Sousuolei;

import com.jiyun.qcloud.dashixummoban.dom.SousuoleiDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sousuoleiDaoConfig;

    private final SousuoleiDao sousuoleiDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sousuoleiDaoConfig = daoConfigMap.get(SousuoleiDao.class).clone();
        sousuoleiDaoConfig.initIdentityScope(type);

        sousuoleiDao = new SousuoleiDao(sousuoleiDaoConfig, this);

        registerDao(Sousuolei.class, sousuoleiDao);
    }
    
    public void clear() {
        sousuoleiDaoConfig.clearIdentityScope();
    }

    public SousuoleiDao getSousuoleiDao() {
        return sousuoleiDao;
    }

}
